;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Monster/DataTable/DT_MonsterTag.DT_MonsterTag
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Debuff",DevComment="")
+GameplayTagList=(Tag="Ability.Movement",DevComment="")
+GameplayTagList=(Tag="Ability.NotCanceledByStun",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Common",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Ultimate",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Unique",DevComment="")
+GameplayTagList=(Tag="Cooldwon.Skill.SpeedBuff",DevComment="")
+GameplayTagList=(Tag="Data.Cooldwon.Duration",DevComment="")
+GameplayTagList=(Tag="Effect.Buff.Speed",DevComment="")
+GameplayTagList=(Tag="Effect.Cooldown",DevComment="")
+GameplayTagList=(Tag="Event.hit",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Gameplay.Magnitude.Duration",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Debug.Ablaze",DevComment="")
+GameplayTagList=(Tag="Input.Attack",DevComment="")
+GameplayTagList=(Tag="Input.Dodge",DevComment="")
+GameplayTagList=(Tag="Input.Sprint",DevComment="")
+GameplayTagList=(Tag="State.CanSprint",DevComment="")
+GameplayTagList=(Tag="State.Cooldown.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="State.Cooldown.StaminaRegenDelay",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Stun",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Wet",DevComment="")
+GameplayTagList=(Tag="State.InAction",DevComment="")
+GameplayTagList=(Tag="State.RemoveOnDeath",DevComment="")
+GameplayTagList=(Tag="State.Rooted",DevComment="")
+GameplayTagList=(Tag="State.Sprint",DevComment="")
+GameplayTagList=(Tag="State.Stamina.Empty",DevComment="")
+GameplayTagList=(Tag="State.UsingUltimate",DevComment="")

