;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Monster/DataTable/DT_MonsterTag.DT_MonsterTag
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Debuff",DevComment="")
+GameplayTagList=(Tag="Ability.Movement",DevComment="")
+GameplayTagList=(Tag="Ability.NotCanceledByStun",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Common",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Ultimate",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Unique",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill.Ablaze",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill.Heal",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill.SpeedBuff",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill.StoneSpear",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill.Unique",DevComment="")
+GameplayTagList=(Tag="Data.Cooldown.Duration",DevComment="")
+GameplayTagList=(Tag="Data.Duration",DevComment="")
+GameplayTagList=(Tag="Data.ManaCharge",DevComment="")
+GameplayTagList=(Tag="Effect.Buff.Speed",DevComment="")
+GameplayTagList=(Tag="Effect.Cooldown",DevComment="")
+GameplayTagList=(Tag="Event.hit",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Trigger",DevComment="")
+GameplayTagList=(Tag="Event.Skill.RockSpear.Fire",DevComment="")
+GameplayTagList=(Tag="Event.Ultimate.Land",DevComment="")
+GameplayTagList=(Tag="Gameplay.Magnitude.Duration",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Debug.Ablaze",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShieldBubble",DevComment="")
+GameplayTagList=(Tag="Input.Attack",DevComment="")
+GameplayTagList=(Tag="Input.Dodge",DevComment="")
+GameplayTagList=(Tag="Input.Shield",DevComment="")
+GameplayTagList=(Tag="Input.Sprint",DevComment="")
+GameplayTagList=(Tag="State.Ablaze",DevComment="")
+GameplayTagList=(Tag="State.Blocking",DevComment="")
+GameplayTagList=(Tag="State.CanSprint",DevComment="")
+GameplayTagList=(Tag="State.Cooldown.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="State.Cooldown.StaminaRegenDelay",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Stun",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Wet",DevComment="")
+GameplayTagList=(Tag="State.Frozen",DevComment="")
+GameplayTagList=(Tag="State.Gaurd.Active",DevComment="")
+GameplayTagList=(Tag="State.Gaurd.Broken",DevComment="")
+GameplayTagList=(Tag="State.Healing",DevComment="")
+GameplayTagList=(Tag="State.Hit",DevComment="")
+GameplayTagList=(Tag="State.InAction",DevComment="")
+GameplayTagList=(Tag="State.RemoveOnDeath",DevComment="")
+GameplayTagList=(Tag="State.Rooted",DevComment="")
+GameplayTagList=(Tag="State.Shield",DevComment="")
+GameplayTagList=(Tag="State.Slowed",DevComment="")
+GameplayTagList=(Tag="State.Sprint",DevComment="")
+GameplayTagList=(Tag="State.Stamina.Empty",DevComment="")
+GameplayTagList=(Tag="State.UsingUltimate",DevComment="")

