;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Monster/DataTable/MonsterTag.MonsterTag
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.NotCanceledByStun",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Debug.Ablaze",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Stun",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Wet",DevComment="")
+GameplayTagList=(Tag="State.RemoveOnDeath",DevComment="")

